<a href="https://colab.research.google.com/github/RichardLDM/AI-foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [9]:
print(pd.__version__)

2.2.2

In [11]:
mydataset = {
    "cars": ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", 'BMW'],
    "counts": [3, 7, 2, 8, 1, 9, 3]
}
print(mydataset)
print("====="*11)

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'], 'counts': [3, 7, 2, 8, 1, 9, 3]}
=======================================================
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [12]:
df.head() # default 5 row

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [14]:
df.tail() # default 5 row

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [16]:
df.shape

(7, 2)

In [17]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [19]:
df.dtypes

cars      object
counts     int64
dtype: object

In [21]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [20]:
df.describe() #default numerical columns only # include="all"

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [28]:
df.iloc[2:] # -1, 1:4

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [31]:
df.loc[:, "counts"] # :, 2, cars, 2:5

0    3
1    7
2    2
3    8
4    1
5    9
6    3
Name: counts, dtype: int64

In [35]:
df[df["counts"] != 3] # df["counts"] > 3, df[df["cars"] == "BMW"]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9

In [37]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [38]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [39]:
df.min()

cars      BMW
counts      1
dtype: object

In [40]:
df.max()

cars      Volvo
counts        9
dtype: object

In [41]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [42]:
df.count()

cars      7
counts    7
dtype: int64

In [43]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [44]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", None, "Ford", 'BMW'],
    "counts": [3, 7, None, 8, 1, 9, None],
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

    cars  counts
0    BMW     3.0
1  Volvo     7.0
2   None     NaN
3  Tesla     8.0
4   None     1.0
5   Ford     9.0
6    BMW     NaN

In [46]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [48]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [51]:
df_missing.dropna(subset=['counts']) # df_missing.dropna(how="all"), df_missing.dropna(axis=1)

    cars  counts
0    BMW     3.0
1  Volvo     7.0
3  Tesla     8.0
4   None     1.0
5   Ford     9.0

In [55]:
df_missing.fillna({"cars": "unkwon", 'counts': 0}) # df_missing.fillna("unknown"), df_missing.fillna(0)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
2  unkwon     0.0
3   Tesla     8.0
4  unkwon     1.0
5    Ford     9.0
6     BMW     0.0

In [61]:
df = pd.read_csv("Titanic-Dataset.csv")
# print(df)
# df.head(30)
df.tail()

# df = pd.read_xlsx("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [63]:
df.to_excel("output.xlsx")

In [64]:
# df = pd.read_xlsx("output.xlsx")
# print(df)
# df.head(30)
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [65]:
# Series => 1D
cars = pd.Series(["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", 'BMW'])
print(cars)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
dtype: object

In [66]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', None, 'Ford', 'BMW']